version: '3'

services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    image: bitrix-${PROJECT_NAME}-mysql
    container_name: bitrix-${PROJECT_NAME}-mysql
    restart: "always"
    volumes:
      # - ./settings/mysql/my.cnf:/etc/my.cnf
      # - ./docker/logs/mysql/:/var/log/
      - ./docker/storage/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "33061:3306"
    networks:
      - bitrix-net

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    image: bitrix-${PROJECT_NAME}-php-apache
    container_name: bitrix-${PROJECT_NAME}-php-apache
    restart: "always"
    # depends_on: 
    #   - mysql
    volumes:
      - ./settings/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./settings/php/:/usr/local/etc/php/conf.d/
      - ./www/:/var/www/html:cached
    ports:
      - "8080:80"
    networks:
      - bitrix-net

  memcached:
    build:
      context: ./docker/memcached
      dockerfile: Dockerfile
    image: bitrix-${PROJECT_NAME}-memcached
    container_name: bitrix-${PROJECT_NAME}-memcached
    restart: "always"
    volumes:
      - ./docker/storage/memcached:/var/lib/memcached
    ports:
      - "11211"
    depends_on:
      - php-apache
    networks:
      - bitrix-net

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    image: bitrix-${PROJECT_NAME}-redis
    container_name: bitrix-${PROJECT_NAME}-redis
    restart: "always"
    volumes:
      - ./docker/storage/redis:/data
    networks:
      - bitrix-net

networks:
  bitrix-net:
